# Generated by Django 5.1.2 on 2024-10-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_covertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covertype',
            new_name='covertypetable',
        ),
    ]
