# Generated by Django 5.1.2 on 2024-10-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_covertype_covertypetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('listprise', models.FloatField()),
                ('price', models.FloatField()),
                ('price50', models.FloatField()),
                ('price100', models.FloatField()),
                ('image', models.FileField(upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.category')),
                ('covertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.covertypetable')),
            ],
        ),
    ]
