# Generated by Django 5.1.2 on 2024-10-25 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_category_product_categorys'),
        ('users', '0002_delete_userlogin_remove_register_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
            ],
        ),
    ]
