# Generated by Django 5.1.2 on 2024-10-30 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_category_product_categorys'),
        ('users', '0004_alter_cart_customerid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ordertb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('orderdate', models.DateTimeField()),
                ('carrier', models.CharField(max_length=20)),
                ('tracking', models.CharField(max_length=20)),
                ('shippingdate', models.DateTimeField()),
                ('transactionid', models.CharField(max_length=20)),
                ('paymentdate', models.DateTimeField()),
                ('paymentstatus', models.CharField(default='pending', max_length=20)),
                ('orderstatus', models.CharField(default='pending', max_length=18)),
                ('ordertotal', models.IntegerField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('count', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ordertb')),
            ],
        ),
    ]
