# Generated by Django 5.1.2 on 2024-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_ordertb_paymentdate_alter_ordertb_shippingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertb',
            name='orderdate',
            field=models.CharField(max_length=20),
        ),
    ]
