# Generated by Django 5.1.2 on 2024-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ordertb_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertb',
            name='carrier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordertb',
            name='paymentdate',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='ordertb',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordertb',
            name='shippingdate',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='ordertb',
            name='tracking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordertb',
            name='transactionid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordertb',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
